package br.com.guisi.simulador.rede.agent.status;

public enum AgentInformationType {

	SWITCH_OPERATION,
	ACTIVE_POWER_LOST,
	REACTIVE_POWER_LOST,
	ACTIVE_POWER_DEMAND,
	REACTIVE_POWER_DEMAND,
	RADIAL_NETWORK,
	SUPPLIED_LOADS_VS_PRIORITY,
	NOT_SUPPLIED_LOADS_VS_PRIORITY,
	MIN_LOAD_CURRENT_VOLTAGE_PU;
}
